eureka:
  instance:
    hostname: client
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8001

spring:
  application:
    name: stockcodeservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/stock_data?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
    password: 123456

logging:
  file:
    name: D:/stock_cloud/stockcode.log  #不指定路径，当前项目下生成日志，指定路径，在路径下生成日志