eureka:
  instance:
    hostname: client
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8004

spring:
  application:
    name: longhubang
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/stock_data?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
    password: 123456