eureka:
  instance:
    hostname: client
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8016

spring:
  application:
    name: FuPan
  jackson:
    time-zone:  GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/stock_data?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: Zhh@271828

chrome:
  url: "http://www.iwencai.com/stockpick/search?typed=1&preParams=&ts=1&f=1&qs=index_rewrite&selfsectsn=&querytype=stock&searchfilter=&tid=stockpick&w=%E6%B6%A8%E5%81%9C%E4%B8%8D%E5%8C%85%E5%90%ABst%EF%BC%9B"


logging:
  file:
    name: /home/zhh/stockdata/logs/fupan.log  #不指定路径，当前项目下生成日志，指定路径，在路径下生成日志
