eureka:
  instance:
    hostname: client
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8013

spring:
  application:
    name: wcxgApplicationService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/stock_data?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
    password: 123456