eureka:
  instance:
    hostname: client
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8013

spring:
  application:
    name: wcxgApplicationService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/stock_data?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
    password: 123456

chrome:
  url: "http://www.iwencai.com/stockpick/search?w=%E5%BC%80%E7%9B%983%E5%88%86%E9%92%9F%E6%8D%A2%E6%89%8B%E7%8E%87%3E2%EF%BC%9B%E5%BC%80%E7%9B%983%E5%88%86%E9%92%9F%E6%88%90%E4%BA%A4%E9%A2%9D%3E5000%E4%B8%87%EF%BC%9B%E5%BC%80%E7%9B%9815%E5%88%86%E9%92%9F%E5%89%8D%E5%A4%8D%E6%9D%83%E6%B6%A8%E5%B9%85%EF%BC%9E3%25%EF%BC%9B%E5%BC%80%E7%9B%98%E5%9C%A8-3%25%E4%BB%A5%E4%B8%8A%EF%BC%9B%E5%BC%80%E7%9B%98%E6%88%90%E4%BA%A4%E9%A2%9D%3E2000%E4%B8%87%EF%BC%9B"
  dirverPath: "C:\\Users\\zhang\\Downloads\\chromedriver_win32\\chromedriver.exe"
